# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-25 12:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateField(default=datetime.datetime.now)),
                ('date_modified', models.DateField(default=datetime.datetime.now)),
                ('student_created', models.IntegerField()),
                ('location', models.IntegerField()),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('units_enrolled', models.IntegerField()),
                ('comments', models.CharField(max_length=100)),
                ('social', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudyNotes',
            fields=[
                ('notes_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('created_by', models.IntegerField()),
                ('created_on', models.DateField(default=datetime.datetime.now)),
                ('location', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('unit_name', models.CharField(max_length=50, unique=True)),
                ('staff', models.IntegerField()),
                ('students', models.IntegerField()),
                ('created_by', models.IntegerField()),
                ('created_on', models.DateField(default=datetime.datetime.now)),
                ('subpages', models.IntegerField()),
                ('notes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UnitSubpage',
            fields=[
                ('subpage_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('unit', models.IntegerField()),
                ('studynotes', models.IntegerField()),
                ('images', models.ImageField(upload_to='')),
                ('quiz', models.CharField(max_length=100)),
            ],
        ),
    ]
