# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-13 17:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notespool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitsubpage',
            name='approval',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unitsubpage',
            name='created_by',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='unitsubpage',
            name='created_on',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='unitsubpage',
            name='subpage_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unitsubpage',
            name='images',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='unitsubpage',
            name='quiz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unitsubpage',
            name='studynotes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='unitsubpage',
            name='subpage_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unitsubpage',
            name='unit',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
