# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-24 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notespool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studynotes',
            name='created_by',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
