# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-27 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notespool', '0002_auto_20170914_0314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
