# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-28 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notespool', '0002_auto_20170728_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
