# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-05 06:02
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notespool', '0002_auto_20171005_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='studynotes',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
