# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-24 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notespool', '0003_studynotes_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='studynotes',
            name='subpage',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
