# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-16 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notespool', '0003_admin_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='comments',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='social',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='units_enrolled',
            field=models.IntegerField(blank=True),
        ),
    ]
