# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-27 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notespool', '0003_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
