# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-24 10:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notespool', '0004_studynotes_subpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studynotes',
            name='date_modified',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
