# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-16 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notespool', '0004_auto_20170816_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='comments',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='social',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='units_enrolled',
            field=models.IntegerField(null=True),
        ),
    ]
