# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-22 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notespool', '0006_auto_20170817_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
