# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-25 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notespool', '0009_auto_20171024_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='studynote',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='subpage',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='unit',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
