# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-31 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notespool', '0009_auto_20170829_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
