# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-26 07:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notespool', '0010_auto_20171026_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.IntegerField(unique=True)),
                ('student', models.IntegerField(unique=True)),
                ('subscription_date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
