# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-25 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notespool', '0010_auto_20171025_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
