# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-31 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notespool', '0010_unit_unit_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='created_by',
            field=models.CharField(max_length=20),
        ),
    ]
