# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-25 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notespool', '0011_document_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
