# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-31 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notespool', '0011_auto_20170831_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='notes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='staff',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='students',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='subpages',
            field=models.IntegerField(null=True),
        ),
    ]
