# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-26 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notespool', '0011_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='student',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='unit_id',
            field=models.IntegerField(null=True),
        ),
    ]
