# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-25 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notespool', '0012_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='studynote',
            field=models.IntegerField(null=True),
        ),
    ]
