# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-26 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notespool', '0012_auto_20171026_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='unit_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
