# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-31 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notespool', '0012_auto_20170831_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
