# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-31 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notespool', '0013_unit_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='approval',
            field=models.NullBooleanField(default=False),
        ),
    ]
